disabled = false
languageCode = "ar"
languageName = "Arabic"
weight = 1
title = "غرفة الفراغ"

[params]
  displayName = "AR"
  isoCode = "ar"
  rtl = true 
  description = "غرفة هادئة نكتب فيها عن التقنية او ممكن نكتب عن اشياء عشوائية عادي , المهم حياك الله"
